server:
  port: 8081
socket-server:
  host: 0.0.0.0
  port: 9092

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  expiration: 86400000 # 24시간

spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/raid_game

management:
  endpoint:
    health:
      show-details: always
      show-components: NEVER
  health:
    defaults:
      enabled: false
    simple:
      enabled: true